### ISSUE TITLE
[BUG] Git Diff doesn't show diff in markdown, but renders it

### ISSUE THREAD

**Issue by deepaksood619** [cweijan/vscode-office#183]
- OS: MAC
- Extension Version: 2.9.5 2023-1-12

Git diff should show diff i.e. changes instead of rendering it in markdown

**Comment by copdips** [comment]
I also need to disable this extension for the moment

**Comment by antoHuman** [comment]
Same for me. There should be at least a setting for this, the `(Working Tree)` comparison with markdown is unreadeable.

**Comment by MallocArray** [comment]
Also looking for a solution here

**Comment by Vigilans** [comment]
According to https://github.com/microsoft/vscode/issues/138525#issuecomment-1847679100, diff editor has its own resource url `git:/...` or `gitlens:/...`, so can be specified to use default editor view in `workbench.editorAssociations`:
```json
    "workbench.editorAssociations": {
        "{git,gitlens}:/**/*.{md,csv}": "default"
    },
```
As such `vscode-office`'s rendering is disabled in diff view.

**NOTE**: Due to a bug in vscode: [editorResolverService.ts#L166-L181](https://github.com/microsoft/vscode/blob/f88bce8fe6a6d2ccd27cbd64bb26853cd8779afa/src/vs/workbench/services/editor/browser/editorResolverService.ts#L166-L181), specifying different editor type for normal view and diff view will make both page in diff view regress into default view. This is because in diff view, left side url is `git:/...`, while right side url is actually `file:/...`.

**Comment by cweijan** [comment]
@Vigilans Thank you for providing it, this setting has been automatically configured in the latest version 3.2.0.
