### ISSUE TITLE
Cannot open links on WYSIWYG markdown view with CTRL/CMD + Mouse Click

### ISSUE THREAD

**Issue by thiagofigcosta** [cweijan/vscode-office#202]
By left clicking some link with CTRL/CMD on WYSIWYG markdown view, the following box open, which is the same behaviour as just clicking the link without holding any key.
![image](https://user-images.githubusercontent.com/10348513/221876471-a58fcfc0-53da-4dc7-b8d8-3e9364719128.png)

By double clicking the link I can open it:
![image](https://user-images.githubusercontent.com/10348513/221876795-ca6b2403-45c6-4b7c-9a12-a2414d373836.png)

Can we open this dialog/open links with CTRL/CMD + Mouse Click ?

I think this makes sense when considering that on the editor view this is the behaviour!

**Comment by elerson** [comment]
+1

**Comment by ceconelli** [comment]
up

**Comment by janiodev** [comment]
+1

**Comment by cweijan** [comment]
Support in version 2.9.6.

**Comment by markNZed** [comment]
This is the closest issue I could find to a problem I'm seeing. I thought I would comment here in case the problem is on my side before I open an issue. I just installed this extension, it looks great. I am running VSCode on files that are inside a docker container on a remote machine. I use a VSCode extension for SSH support to connect to the machine and then another VSCode extension allows attaching to a docker container on the machine. When I double click a link I get a message: "Do you want Code to open the external website" but my link in the file I am editing is a relative link to a file "../README.md" Code is trying to open a link that looks like `https://vscode-remote+attached-002dcontainer-002b7b22636f6e7461696e65724e66f636b65725f7461736b666c6f772d6465765f31222c2273657474696e6773223a7b22686f7374223a227373683a2f2f73657276657231227d7d.vscode-resource.vscode-cdn.net/app/README.md` which does not work. I guess there is an issue to do with remote containers ? Thanks for any pointers

It seems a link like this open in a new VSCode window. Note this is only SSH not to the dev container:
`vscode://vscode-remote/ssh-remote+serverName/app/README.md:1:1`

I found some information about link formats at https://github.com/microsoft/vscode-remote-release/issues/4779

It is still unclear to me it is is possible to open links on a remote container. It seems an even bigger ask to have them open in a new tab instead of a new VSCode window. One thing to note is that the URL this extension creates starts with HTTPS so this is not what we want. Maybe a first step is to be able to configure the prefix used to open relative links?
